export const GET_CONTENT_TYPES = 'GET_CONTENT_TYPES';
export const GET_CONTENT_TYPES_SUCCEEDED = 'GET_CONTENT_TYPES_SUCCEEDED';

export const GET_CONTENT_LIST_CONTENT_TYPE = 'GET_CONTENT_LIST_CONTENT_TYPE';
export const GET_CONTENT_LIST_CONTENT_TYPE_SUCCEEDED = 'GET_CONTENT_LIST_CONTENT_TYPE_SUCCEEDED'
