export const GET_CONFIG = 'GET_CONFIG';
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';

export const GET_CONTENT_LIST_CONTENT_TYPE = 'GET_CONTENT_LIST_CONTENT_TYPE';
export const GET_CONTENT_LIST_CONTENT_TYPE_SUCCEEDED = 'GET_CONTENT_LIST_CONTENT_TYPE_SUCCEEDED'
