export const APPROVAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const REPORT_STATUS = {
  ...APPROVAL_STATUS,
  BLOCKED: 'BLOCKED',
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
} as const;

export enum REPORT_REASON {
  BAD_LANGUAGE = 'BAD_LANGUAGE',
  DISCRIMINATION = 'DISCRIMINATION',
  OTHER = 'OTHER',
};

export const COMMENT_STATUS = {
  ...APPROVAL_STATUS,
  BLOCKED: 'BLOCKED',
  OPEN: 'OPEN',
  REMOVED: 'REMOVED',
  TO_REVIEW: 'TO_REVIEW',
  UNKNOWN: 'UNKNOWN',
} as const;
