export const APPROVAL_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const REPORT_STATUS = {
  RESOLVED: "RESOLVED",
  OPEN: "OPEN",
};

export const REPORT_REASON = {
  BAD_LANGUAGE: "BAD_LANGUAGE",
  DISCRIMINATION: "DISCRIMINATION",
  OTHER: "OTHER",
};

export const COMMENT_STATUS = {
  UNKNOWN: "UNKNOWN",
  BLOCKED: "BLOCKED",
  OPEN: "OPEN",
  REMOVED: "REMOVED",
  TO_REVIEW: "TO_REVIEW",
  ...APPROVAL_STATUS,
};
